client_v1: client_v1.c ./help/help_menu.c ./socket_helpers/bluetoothSocketConnect.c ./buff_logic/buff_read.c
	gcc -o client_v1 client_v1.c ./help/help_menu.c ./buff_logic/buff_read.c ./socket_helpers/bluetoothSocketConnect.c -lbluetooth
